spring:
  application:
    name: files
  profiles: 
    active: dev 
  config: 
    import: optional:file:.env[.properties] 
  servlet:
    multipart:
      max-file-size: 2GB
server:
  port: 8083

api:
  folder-path: ${PATH}