spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key
server:
  port: 8080

api:
  public-key: classpath:public.key