FROM eclipse-temurin:26-jdk AS build
WORKDIR /app

COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
RUN ./mvnw dependency:go-offline

COPY src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:26-jre-alpine
WORKDIR /app
 
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8082
CMD ["java", "-jar", "app.jar"]