spring:
  application:
    name: auth
  profiles: 
    active: dev 
  config: 
    import: optional:file:.env[.properties] 
api:
  public-key:  classpath:public.key
  private-key: classpath:private.key
 
server:
  port: 8081