CREATE TYPE Mimetype AS ENUM ('MP4', 'ACC', 'MP3', 'WAV', 'WEBM', 'OGG', 'PNG', 'JPEG', 'GIF', 'PDF');

CREATE TABLE IF NOT EXISTS data (
    id BIGSERIAL PRIMARY KEY,
    duration INTEGER UNIQUE NOT NULL,
    file_length BIGINT UNIQUE NOT NULL, 
    mimetype Mimetype NOT NULL,
    physical_path VARCHAR(100) UNIQUE NOT NULL,
    file_path VARCHAR(100) UNIQUE NOT NULL,
    created_file TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file (
    id BIGSERIAL PRIMARY KEY,
    data_id BIGINT,
    name VARCHAR(100) NOT NULL,
    hash VARCHAR(64) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_data FOREIGN KEY (data_id) REFERENCES data (id)
);

